-- ITI VAV MANAGEMENT SYSTEM - Supabase database
-- Run this entire file in Supabase SQL Editor.

create table if not exists public.si_data (id bigint generated by default as identity primary key, si_name text not null, trade_name text not null, batch text not null, on_roll_batch text not null, extra_charge text, qualification text, mobile text, joining_date date, created_at timestamptz default now());
create table if not exists public.admission_data (id bigint generated by default as identity primary key, year text not null, no_of_seat integer not null, trade text not null, approved integer not null, filled integer not null, created_at timestamptz default now());
create table if not exists public.year_wise_result (id bigint generated by default as identity primary key, trade text not null, batch text not null, year text not null, total_student integer not null, present_in_exam integer not null, pass integer not null, fail integer not null, created_at timestamptz default now());
create table if not exists public.tot_attend (id bigint generated by default as identity primary key, si_name text not null, trade_subject text not null, attended text not null, duration text not null, from_date date not null, to_date date not null, created_at timestamptz default now());
create table if not exists public.guest_faculty (id bigint generated by default as identity primary key, lecture_date date not null, faculty_name text not null, industry_name text not null, topic_details text not null, participants integer not null, created_at timestamptz default now());
create table if not exists public.placement_iti_vav (id bigint generated by default as identity primary key, event_date date not null, industry_name text not null, industries_count integer not null, candidates_participated integer not null, candidates_selected integer not null, created_at timestamptz default now());
create table if not exists public.placement_by_si (id bigint generated by default as identity primary key, si_name text not null, trade_name text not null, batch text not null, last_on_roll integer not null, rojgari integer not null, swarojgari integer not null, ucch_abhyas integer not null, gn integer not null, sebc integer not null, sc integer not null, st integer not null, created_at timestamptz default now());
create table if not exists public.provisional_letters (id bigint generated by default as identity primary key, si_name text not null, trade_name text not null, batch text not null, year text not null, trainees_appeared integer not null, offer_letters integer not null, percentage numeric(7,2), created_at timestamptz default now());
create table if not exists public.equivalence_certificate (id bigint generated by default as identity primary key, si_name text not null, trade_name text not null, batch text not null, year text not null, total_admitted integer not null, eligible_certificate integer not null, got_certificate integer not null, created_at timestamptz default now());
create table if not exists public.female_admitted (id bigint generated by default as identity primary key, trade_name text not null, total_trainees integer not null, female_trainees integer not null, created_at timestamptz default now());
create table if not exists public.extra_activity (id bigint generated by default as identity primary key, activity_details text not null, activity_date date not null, created_at timestamptz default now());
create table if not exists public.ojt_by_si (id bigint generated by default as identity primary key, trade_name text not null, batch_no text not null, admitted_trainees integer not null, industry_name text not null, trainees_ojt integer not null, ojt_duration text not null, from_date date not null, to_date date not null, created_at timestamptz default now());
create table if not exists public.industrial_visit (id bigint generated by default as identity primary key, trade_name text not null, batch_no text not null, trainees_sent integer not null, industry_name text not null, visit_date date not null, created_at timestamptz default now());
create table if not exists public.vocational_campaign (id bigint generated by default as identity primary key, campaign_date date not null, campaign_details text not null, school_name_address text not null, created_at timestamptz default now());

-- Security: only logged-in users can use the dashboard.
do $$ declare t text; begin
  foreach t in array array['si_data','admission_data','year_wise_result','tot_attend','guest_faculty','placement_iti_vav','placement_by_si','provisional_letters','equivalence_certificate','female_admitted','extra_activity','ojt_by_si','industrial_visit','vocational_campaign'] loop
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "authenticated full access" on public.%I', t);
    execute format('create policy "authenticated full access" on public.%I for all to authenticated using (true) with check (true)', t);
  end loop;
end $$;
